### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by erdnaxelaweb** [Novactive/NovaeZSolrSearchExtraBundle#3]
https://lucene.apache.org/solr/guide/6_6/highlighting.html

**Comment by andrerom** [comment]
Note: Highlighting and spell checking is probably something that should be fixed in upstream [SolrBundle](https://github.com/ezsystems/ezplatform-solr-search-engine) which this one extends so more people can benefit. We'll happily attempt tp mention anyone willing to try contributing on that 😃
